### PR TITLE
EXOGTN-2433: Code Refactoring of Group Management (#253)

### PR DESCRIPTION
**Pull request by ghost**
* EXOGTN-2433: Code Refactoring of Group Management

* EXOGTN-2433 : Added Unit test and refactored GroupManagement

Co-authored-by: Ali HAMDI <ahamdi@exoplatform.com>
(cherry picked from commit 77d81d9f1f868504916d4805d15e51f9bf9104a8)

### CODE REVIEW

**Review by mzorai — DISMISSED** [review]
LGTM

**Review by rdenarie — DISMISSED** [review]
LGTM

**Review by ahamdi — DISMISSED** [review]
Unit tests fixed.
LGTM

**Comment by ahamdi** [comment]
@hbenali Please check again from your side before merging.

**Review by rdenarie — APPROVED** [review]
LGTM

**Pull request merged**
